# simple postgres install for local development

services:
  db:
    image: postgres:15
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  database:
